import 'server-only'
import Anthropic from '@anthropic-ai/sdk'
import { devLog, devLogOnly } from '@/lib/inngest/dev'

// Article generation. Calls Claude with the bio + name + tagline + socials
// and returns { headline, subheadline, body, slug }. The slug always
// contains a 6-char random suffix so collisions are vanishingly rare; the
// Inngest workflow still re-checks `articles.slug` uniqueness before insert.

const MODEL = 'claude-opus-4-7'

export interface GeneratedArticle {
  headline: string
  subheadline: string
  body: string
  slug: string
}

export interface GenerateArticleArgs {
  display_name: string
  tagline?: string | null
  bio: string
  social_links: Array<{ platform: string; value: string }>
}

const SYSTEM = `You are a staff writer at "The Norm," a profile publication. You write 250–400 word profiles in a professional, slightly admiring but factual tone. Match the editorial register of The Atlantic or NYT profile pieces.

Rules:
- Avoid sycophantic language. Avoid invented quotes. Stick to what the bio claims.
- Headline: at most 80 chars, declarative, no clickbait.
- Subheadline: at most 140 chars.
- Body: 250–400 words, plain text, paragraphs separated by \\n\\n. No markdown. No HTML.
- Output JSON only, no preamble, with this shape: { "headline": string, "subheadline": string, "body": string }`

export async function generateArticle(args: GenerateArticleArgs): Promise<GeneratedArticle> {
  const slugBase = slugify(args.display_name)
  const slug = `${slugBase}-${randomSuffix()}`

  if (devLogOnly('anthropic')) {
    devLog('anthropic', 'generateArticle (dev-mode stub)', { display_name: args.display_name })
    return {
      headline: `${args.display_name}, in their own words`,
      subheadline: args.tagline ?? 'A profile by The Norm.',
      body:
        `${args.display_name} is the subject of this dev-mode placeholder profile.\n\n` +
        `${args.bio.slice(0, 600)}\n\n` +
        `This text is not generated by Claude — DEV_MODE_LOG_ONLY is enabled.`,
      slug,
    }
  }

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not set')

  const client = new Anthropic({ apiKey })
  const social = args.social_links
    .map((l) => `${l.platform}: ${l.value}`)
    .join('\n') || '(none)'
  const prompt = `Person:
- Name: ${args.display_name}
- Tagline: ${args.tagline ?? '(none)'}
- Bio: """${args.bio}"""
- Social:
${social}`

  const resp = await client.messages.create({
    model: MODEL,
    max_tokens: 1500,
    system: SYSTEM,
    messages: [{ role: 'user', content: prompt }],
  })
  const text = resp.content
    .filter((b): b is Anthropic.TextBlock => b.type === 'text')
    .map((b) => b.text)
    .join('')
    .trim()
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/```$/i, '')
    .trim()
  const parsed = JSON.parse(text) as Omit<GeneratedArticle, 'slug'>
  if (
    typeof parsed.headline !== 'string' ||
    typeof parsed.subheadline !== 'string' ||
    typeof parsed.body !== 'string'
  ) {
    throw new Error('Article JSON missing required fields')
  }
  return {
    headline: parsed.headline.slice(0, 80),
    subheadline: parsed.subheadline.slice(0, 140),
    body: parsed.body,
    slug,
  }
}

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'profile'
}

function randomSuffix(): string {
  // 6 lowercase alphanumeric chars. Crypto-random to avoid predictable URLs.
  const bytes = new Uint8Array(6)
  crypto.getRandomValues(bytes)
  const alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789'
  return Array.from(bytes, (b) => alphabet[b % alphabet.length]).join('')
}
